# Generated by Django 2.1.7 on 2020-07-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='c_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
