# Generated by Django 2.1.7 on 2020-07-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0002_auto_20200707_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='c_id',
            field=models.CharField(max_length=20),
        ),
    ]
